package com.example.greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.example.greendao.ZI_NoteListDao;
import com.example.greendao.ZI_EmailDataDao;
import com.example.greendao.ZI_BlogDataDao;
import com.example.greendao.ZI_WorkHistoryDataDao;
import com.example.greendao.ZI_TeachDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        ZI_NoteListDao.createTable(db, ifNotExists);
        ZI_EmailDataDao.createTable(db, ifNotExists);
        ZI_BlogDataDao.createTable(db, ifNotExists);
        ZI_WorkHistoryDataDao.createTable(db, ifNotExists);
        ZI_TeachDataDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        ZI_NoteListDao.dropTable(db, ifExists);
        ZI_EmailDataDao.dropTable(db, ifExists);
        ZI_BlogDataDao.dropTable(db, ifExists);
        ZI_WorkHistoryDataDao.dropTable(db, ifExists);
        ZI_TeachDataDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(ZI_NoteListDao.class);
        registerDaoClass(ZI_EmailDataDao.class);
        registerDaoClass(ZI_BlogDataDao.class);
        registerDaoClass(ZI_WorkHistoryDataDao.class);
        registerDaoClass(ZI_TeachDataDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
