package com.example.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.greendao.ZI_NoteList;
import com.example.greendao.ZI_EmailData;
import com.example.greendao.ZI_BlogData;
import com.example.greendao.ZI_WorkHistoryData;
import com.example.greendao.ZI_TeachData;

import com.example.greendao.ZI_NoteListDao;
import com.example.greendao.ZI_EmailDataDao;
import com.example.greendao.ZI_BlogDataDao;
import com.example.greendao.ZI_WorkHistoryDataDao;
import com.example.greendao.ZI_TeachDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig zI_NoteListDaoConfig;
    private final DaoConfig zI_EmailDataDaoConfig;
    private final DaoConfig zI_BlogDataDaoConfig;
    private final DaoConfig zI_WorkHistoryDataDaoConfig;
    private final DaoConfig zI_TeachDataDaoConfig;

    private final ZI_NoteListDao zI_NoteListDao;
    private final ZI_EmailDataDao zI_EmailDataDao;
    private final ZI_BlogDataDao zI_BlogDataDao;
    private final ZI_WorkHistoryDataDao zI_WorkHistoryDataDao;
    private final ZI_TeachDataDao zI_TeachDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        zI_NoteListDaoConfig = daoConfigMap.get(ZI_NoteListDao.class).clone();
        zI_NoteListDaoConfig.initIdentityScope(type);

        zI_EmailDataDaoConfig = daoConfigMap.get(ZI_EmailDataDao.class).clone();
        zI_EmailDataDaoConfig.initIdentityScope(type);

        zI_BlogDataDaoConfig = daoConfigMap.get(ZI_BlogDataDao.class).clone();
        zI_BlogDataDaoConfig.initIdentityScope(type);

        zI_WorkHistoryDataDaoConfig = daoConfigMap.get(ZI_WorkHistoryDataDao.class).clone();
        zI_WorkHistoryDataDaoConfig.initIdentityScope(type);

        zI_TeachDataDaoConfig = daoConfigMap.get(ZI_TeachDataDao.class).clone();
        zI_TeachDataDaoConfig.initIdentityScope(type);

        zI_NoteListDao = new ZI_NoteListDao(zI_NoteListDaoConfig, this);
        zI_EmailDataDao = new ZI_EmailDataDao(zI_EmailDataDaoConfig, this);
        zI_BlogDataDao = new ZI_BlogDataDao(zI_BlogDataDaoConfig, this);
        zI_WorkHistoryDataDao = new ZI_WorkHistoryDataDao(zI_WorkHistoryDataDaoConfig, this);
        zI_TeachDataDao = new ZI_TeachDataDao(zI_TeachDataDaoConfig, this);

        registerDao(ZI_NoteList.class, zI_NoteListDao);
        registerDao(ZI_EmailData.class, zI_EmailDataDao);
        registerDao(ZI_BlogData.class, zI_BlogDataDao);
        registerDao(ZI_WorkHistoryData.class, zI_WorkHistoryDataDao);
        registerDao(ZI_TeachData.class, zI_TeachDataDao);
    }
    
    public void clear() {
        zI_NoteListDaoConfig.getIdentityScope().clear();
        zI_EmailDataDaoConfig.getIdentityScope().clear();
        zI_BlogDataDaoConfig.getIdentityScope().clear();
        zI_WorkHistoryDataDaoConfig.getIdentityScope().clear();
        zI_TeachDataDaoConfig.getIdentityScope().clear();
    }

    public ZI_NoteListDao getZI_NoteListDao() {
        return zI_NoteListDao;
    }

    public ZI_EmailDataDao getZI_EmailDataDao() {
        return zI_EmailDataDao;
    }

    public ZI_BlogDataDao getZI_BlogDataDao() {
        return zI_BlogDataDao;
    }

    public ZI_WorkHistoryDataDao getZI_WorkHistoryDataDao() {
        return zI_WorkHistoryDataDao;
    }

    public ZI_TeachDataDao getZI_TeachDataDao() {
        return zI_TeachDataDao;
    }

}
