package com.example.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ZI__BLOG_DATA".
 */
public class ZI_BlogData {

    private Long id;
    /** Not-null value. */
    private String sort;
    /** Not-null value. */
    private String blog;

    public ZI_BlogData() {
    }

    public ZI_BlogData(Long id) {
        this.id = id;
    }

    public ZI_BlogData(Long id, String sort, String blog) {
        this.id = id;
        this.sort = sort;
        this.blog = blog;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSort() {
        return sort;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /** Not-null value. */
    public String getBlog() {
        return blog;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBlog(String blog) {
        this.blog = blog;
    }

}
