package com.example.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ZI__EMAIL_DATA".
 */
public class ZI_EmailData {

    private Long id;
    /** Not-null value. */
    private String sort;
    /** Not-null value. */
    private String email;

    public ZI_EmailData() {
    }

    public ZI_EmailData(Long id) {
        this.id = id;
    }

    public ZI_EmailData(Long id, String sort, String email) {
        this.id = id;
        this.sort = sort;
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSort() {
        return sort;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

}
