package com.example.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ZI__NOTE_LIST".
 */
public class ZI_NoteList {

    private Long id;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String date;
    /** Not-null value. */
    private String url;

    public ZI_NoteList() {
    }

    public ZI_NoteList(Long id) {
        this.id = id;
    }

    public ZI_NoteList(Long id, String title, String date, String url) {
        this.id = id;
        this.title = title;
        this.date = date;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

}
