package com.example.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ZI__TEACH_DATA".
 */
public class ZI_TeachData {

    private Long id;
    /** Not-null value. */
    private String schoolName;
    /** Not-null value. */
    private String degree;
    /** Not-null value. */
    private String manager;
    /** Not-null value. */
    private String startTime;
    /** Not-null value. */
    private String endTime;
    /** Not-null value. */
    private String grade;

    public ZI_TeachData() {
    }

    public ZI_TeachData(Long id) {
        this.id = id;
    }

    public ZI_TeachData(Long id, String schoolName, String degree, String manager, String startTime, String endTime, String grade) {
        this.id = id;
        this.schoolName = schoolName;
        this.degree = degree;
        this.manager = manager;
        this.startTime = startTime;
        this.endTime = endTime;
        this.grade = grade;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSchoolName() {
        return schoolName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /** Not-null value. */
    public String getDegree() {
        return degree;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /** Not-null value. */
    public String getManager() {
        return manager;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setManager(String manager) {
        this.manager = manager;
    }

    /** Not-null value. */
    public String getStartTime() {
        return startTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /** Not-null value. */
    public String getEndTime() {
        return endTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /** Not-null value. */
    public String getGrade() {
        return grade;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGrade(String grade) {
        this.grade = grade;
    }

}
