package com.example.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ZI__WORK_HISTORY_DATA".
 */
public class ZI_WorkHistoryData {

    private Long id;
    /** Not-null value. */
    private String workTitle;
    /** Not-null value. */
    private String compayName;
    /** Not-null value. */
    private String location;
    /** Not-null value. */
    private String startTime;
    /** Not-null value. */
    private String endTime;
    /** Not-null value. */
    private String scribe;

    public ZI_WorkHistoryData() {
    }

    public ZI_WorkHistoryData(Long id) {
        this.id = id;
    }

    public ZI_WorkHistoryData(Long id, String workTitle, String compayName, String location, String startTime, String endTime, String scribe) {
        this.id = id;
        this.workTitle = workTitle;
        this.compayName = compayName;
        this.location = location;
        this.startTime = startTime;
        this.endTime = endTime;
        this.scribe = scribe;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getWorkTitle() {
        return workTitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWorkTitle(String workTitle) {
        this.workTitle = workTitle;
    }

    /** Not-null value. */
    public String getCompayName() {
        return compayName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompayName(String compayName) {
        this.compayName = compayName;
    }

    /** Not-null value. */
    public String getLocation() {
        return location;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLocation(String location) {
        this.location = location;
    }

    /** Not-null value. */
    public String getStartTime() {
        return startTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /** Not-null value. */
    public String getEndTime() {
        return endTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /** Not-null value. */
    public String getScribe() {
        return scribe;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setScribe(String scribe) {
        this.scribe = scribe;
    }

}
