package com.example.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.greendao.ZI_WorkHistoryData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ZI__WORK_HISTORY_DATA".
*/
public class ZI_WorkHistoryDataDao extends AbstractDao<ZI_WorkHistoryData, Long> {

    public static final String TABLENAME = "ZI__WORK_HISTORY_DATA";

    /**
     * Properties of entity ZI_WorkHistoryData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property WorkTitle = new Property(1, String.class, "workTitle", false, "WORK_TITLE");
        public final static Property CompayName = new Property(2, String.class, "compayName", false, "COMPAY_NAME");
        public final static Property Location = new Property(3, String.class, "location", false, "LOCATION");
        public final static Property StartTime = new Property(4, String.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(5, String.class, "endTime", false, "END_TIME");
        public final static Property Scribe = new Property(6, String.class, "scribe", false, "SCRIBE");
    };


    public ZI_WorkHistoryDataDao(DaoConfig config) {
        super(config);
    }
    
    public ZI_WorkHistoryDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ZI__WORK_HISTORY_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"WORK_TITLE\" TEXT NOT NULL ," + // 1: workTitle
                "\"COMPAY_NAME\" TEXT NOT NULL ," + // 2: compayName
                "\"LOCATION\" TEXT NOT NULL ," + // 3: location
                "\"START_TIME\" TEXT NOT NULL ," + // 4: startTime
                "\"END_TIME\" TEXT NOT NULL ," + // 5: endTime
                "\"SCRIBE\" TEXT NOT NULL );"); // 6: scribe
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ZI__WORK_HISTORY_DATA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ZI_WorkHistoryData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getWorkTitle());
        stmt.bindString(3, entity.getCompayName());
        stmt.bindString(4, entity.getLocation());
        stmt.bindString(5, entity.getStartTime());
        stmt.bindString(6, entity.getEndTime());
        stmt.bindString(7, entity.getScribe());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ZI_WorkHistoryData readEntity(Cursor cursor, int offset) {
        ZI_WorkHistoryData entity = new ZI_WorkHistoryData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // workTitle
            cursor.getString(offset + 2), // compayName
            cursor.getString(offset + 3), // location
            cursor.getString(offset + 4), // startTime
            cursor.getString(offset + 5), // endTime
            cursor.getString(offset + 6) // scribe
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ZI_WorkHistoryData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWorkTitle(cursor.getString(offset + 1));
        entity.setCompayName(cursor.getString(offset + 2));
        entity.setLocation(cursor.getString(offset + 3));
        entity.setStartTime(cursor.getString(offset + 4));
        entity.setEndTime(cursor.getString(offset + 5));
        entity.setScribe(cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ZI_WorkHistoryData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ZI_WorkHistoryData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
